version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      hello-world-mongo:
    depends_on:
      - db
  db:
    image: mongo:3
    volumes:
      - db:/data/db
    networks:
      hello-world-mongo:
networks:
  hello-world-mongo:
volumes:
  db:
